ALTER DATABASE `java_ecommerce` CHARACTER SET utf8 COLLATE utf8_general_ci;
INSERT INTO users (emailId, enabled, password)
VALUES ('admin@gmail.com', 1, 'admin');
INSERT INTO authorities (authorities, emailId)
VALUES ('ROLE_ADMIN', 'admin@gmail.com');

INSERT INTO `product` (`productId`, `description`, `name`, `overview`, `quantity`, `price`, `category`, `salePrice`) VALUES
(1, 'iPhone 6s Plus 64 GB được nâng cấp độ phân giải camera sau lên 12 MP (thay vì 8 MP như trên iPhone 6 Plus), camera cho tốc độ lấy nét và chụp nhanh, thao tác chạm để chụp nhẹ nhàng. Chất lượng ảnh trong các điều kiện chụp khác nhau tốt.', 'iPhone 6s Plus', 'Điện thoại iPhone 6s Plus 64GB', 20, 22.99, 'Smartphone', 10),
(2, 'Khả năng chống nước, chống bụi an toàn cho máy của Galaxy S7 Edge\r\nNhờ đạt chuẩn IP68 nên hoàn toàn có thể bảo vệ được tốt cho Galaxy S7 Edge khi vô tình dính nước mưa hay làm đổ nước, cho bạn thêm an tâm trong quá trình sử dụng.', 'Samsung Galaxy S7', 'Điện thoại Samsung Galaxy S7 Edge', 20, 18.49, 'Smartphone', 10),
(3, 'Đầu tiên là mặt trước HTC 10, nổi bật lên ống kính camera trước rất lớn tuy rằng độ phân giải 5 MP, phím cảm biến ở mặt dưới. Cạnh dưới của máy, hai phím điều hướng cảm ứng nằm hai bên, không đặt ở trong màn hình để tăng diện tích sử dụng.', 'HTC 10\r\n', 'Điện thoại HTC 10', 20, 16.99, 'Smartphone', 10),
(4, 'Màn hình độ phân giải 4K trên Xperia Z5 Premium Dual cùng nhiều công nghệ độc quyền của Sony như: Triluminos (nâng cấp chất lượng hình ảnh), X-Reality™ (tối ưu hóa màu sắc, độ nét)... sẽ giúp bạn trải nghiệm hình ảnh, video 1 cách tuyệt vời nhất.', 'Sony Xperia Z5', 'Điện thoại Sony Xperia Z5 Premium Dual', 20, 15.49, 'Smartphone', 10),
(5, 'Thiết kế sang trọng\r\nGalaxy A9 Pro vẫn sở hữu phong cách thiết kế tương tự các anh em dòng Galaxy A 2016 của mình với khung viền kim loại chắc chắn cùng 2 mặt kính cường lực trước sau sang trọng.', 'Samsung Galaxy A9 Pro', 'Galaxy A9 Pro là smartphone lớn nhất trong gia đình Galaxy A 2016. Máy sở hữu viên pin khủng dung lượng 5.000 mAh cùng 4 GB RAM mạnh mẽ.', 20, 11.99, 'Smartphone', 10),
(6, 'iPhone SE giữ nguyên thiết kế tinh tế, sang trọng\r\niPhone SE vẫn giữ nguyên thiết kế trên người tiền nhiệm iPhone 5S và không có nhiều sự thay đổi. Khi đặt 2 thiết bị cạnh nhau thì bạn sẽ không thể nào phân biệt được đâu là iPhone 5S và đâu là iPhone SE.', 'iPhone SE 16GB', 'Chiếc iPhone 4 inch mới với nhiều cải tiến với tên gọi iPhone SE.', 20, 11.49, 'Smartphone', 10),
(7, 'Thiết kế đối xứng mạnh mẽ Sony Xperia X vẫn mang trong mình bóng dáng của các anh em dòng Z Series với phong cách thiết kế omibaland quen thuộc. Máy trông vẫn rất sang trọng đúng phong cách rất “Sony”.', 'Sony Xperia X', 'Sony vừa giới thiệu dòng sản phẩm X Serie mới của hãng trong năm 2016 tại triển lãm MWC. Xperia X là chiếc smartphone tầm trung mới với nhiều điểm nhấn đáng chú ý.', 20, 11.9, 'Smartphone', 10),
(8, 'Thiết kế sang trọng, tinh xảo\r\nHuawei P9 mang trong mình thiết kế sang trọng và tinh tế với khung viền kim loại cùng 4 góc được bo cong mềm mại đem lại cảm giác cầm nắm khá thoải mái.', 'Huawei P9\r\n', 'Mới đây Huawei đã chính thức giới thiệu smartphone đầu bảng là chiếc Huawei P9 với điểm nhấn là camera kép hợp tác sản xuất cùng Leica.', 20, 10.99, 'Smartphone', 10),
(9, 'Thiết kế mới trên Galaxy A7 phiên bản 2016\r\nSo với A7 đời đầu khá vuông vức các góc cạnh thì với Galaxy A7 2016 được thay đổi hoàn toàn, mềm mại hơn nhưng vẫn khác biệt.\r\nKhung kim loại viền quanh máy tạo nên vẻ chắc chắn.', 'Samsung Galaxy A7', 'Samsung Galaxy A7 (2016) đem lại màn hình to hơn, cấu hình mạnh mẽ hơn cùng nhiều tiện ích tốt cho bạn.', 20, 9.99, 'Smartphone', 10),
(10, 'Oppo F1 Plus được thiết kế lấy cảm hứng từ nhà táo cắn dở\r\nKhông thể phủ nhận Oppo F1 Plus lấy cảm hứng thiết kế rất nhiều từ dòng iPhone 6, mặt lưng hoàn toàn giống cho tới phần camera lồi.', 'OPPO F1 Plus', 'Oppo F1 Plus có một thiết kế mặt trước rất đẹp, trang bị cảm biến vân tay.', 20, 9.99, 'Smartphone', 10),
(11, 'Màu sắc bắt mắt\r\nLà chiếc laptop hướng tới việc giải trí là chính nên hãng rất chú trọng đến phần màu sắc của tổng thể máy với tông đỏ, xanh dương và bạc.\r\nMáy khá gọn nhẹ khi chỉ nặng vỏn vẹn 1 kg.', 'Laptop Lenovo IdeaPad 100S 11IBY Z3735/2GB/32GB/Win10', 'Lenovo IdeaPad 100S 11IBY có mức giá rẻ bất ngờ, thiết kế màu sắc dễ thương phù hợp mang theo bên mình để giải trí.', 20, 3.99, 'Laptop', 10),
(12, 'Cấu hình vừa đủ cho công việc và giải trí nhẹ nhàng\r\nSử dụng CPU Celeron, tốc độ 2.16 GHz, máy chỉ có 1 khe cắm RAM 2 GB và bạn có thể nâng cấp lên tối đa 8 GB.\r\nKhi sử dụng một thời gian, bạn nên thay thanh RAM với dung lượng lớn hơn (tối đa 8 GB)', 'Laptop Lenovo IdeaPad 100 14IBY N2840/2GB/500GB/Win10', 'Lenovo IdeaPad 100 14IBY có mức giá thấp ai cũng có thể sở hữu, phù hợp với các nhu cầu sử dụng đơn giản.', 20, 5.49, 'Laptop', 10),
(13, 'Phần cứng ổn\r\nHP Pavilion 11 S001TU N3050 không phải là chiếc máy chuyên chơi game hay sử dụng các ứng dụng nặng, máy phù hợp hơn với học sinh hay nhân viên làm việc, giải trí đơn giản.', 'Laptop HP Pavilion 11 S001TU N3050/2GB/500GB/Win10', 'HP Pavilion 11 S001TU N3050 là chiếc laptop có thiết kế nhỏ gọn, cấu hình khá ổn và trên hết là mức giá rất tốt.', 20, 5.99, 'Laptop', 10),
(14, 'Cấu hình phù hợp với các chương trình nhẹ nhàng\r\nMáy sử dụng chip xử lý Celeron để đảm bảo giá thành tốt, RAM 4 GB là điểm sáng giúp máy vận hành không quá chậm, bạn có thể nâng cấp lên tối đa 8 GB.\r\nỔ cứng HDD 500 GB thoải mái lưu trữ dữ liệu.', 'Laptop Acer ES1 431 N3060/4GB/500GB/Win10', 'Acer ES1 431 N306 mang lại hiệu năng sử dụng đơn giản để học tập hay giải trí cho bạn.', 20, 5.99, 'Laptop', 10),
(15, 'Cấu hình được cải thiện\r\nKhông có quá nhiều sự khác biệt so với bản Asus E402MA, Asus E402SA được sử dụng chip Celeron phiên bản tốt hơn là N3050, giúp máy hoạt động có phần nhẹ nhàng hơn.\r\nMáy vẫn trang bị đủ ổ cứng HDD 500 GB, RAM sẵn 2 GB.', 'Laptop Asus E402SA N3050/2GB/500GB/Win10', 'Asus E402SA N3050 là bản nâng cấp nhẹ với chip xử lý Celeron cho khả năng hoạt động tốt hơn.', 20, 6.29, 'Laptop', 10),
(16, 'Màn hình lớn\r\nMáy được trang bị màn hình lớn 15.6 inch, cùng với đó là công nghệ hiển thị HD WLED TrueLife có độ tương phản cao.', 'Laptop Dell Inspiron 3552 N3050/2GB/500GB/Win10', 'Dell Inspiron 3552 N3050 thuộc dòng máy giá rẻ nhưng được trang bị màn hình lớn, bàn phím đầy đủ cụm số tiện ích.', 20, 6.49, 'Laptop', 10),
(17, 'Màn hình nổi bật, hiển thị đẹp\r\nVẫn là màn hình HD 14 inch, và có phần nhỉnh hơn thế hệ trước bởi khả năng hiển thị độ sáng tốt, màu sắc đẹp nhờ công nghệ Active Matrix TFT Colour LCD.', 'Laptop Acer ES1 431 N3710/4GB/500GB/Win10', 'Laptop Acer ES1 431 N3710 có cấu hình ổn định, gọn nhẹ, thích hợp với mọi lứa tuổi người dùng.', 20, 6.99, 'Laptop', 10),
(18, 'Là một sản phẩm không nhiều thay đổi trong thiết kế nhưng được được trang bị cấu hình và giá thành phù hợp hơn, HP 14 ac198TU xứng đáng là một lựa chọn tốt cho công việc và giải trí của người dùng ở phân khúc giá rẻ.', 'Laptop HP 14 ac198TU N3700/2GB/500GB/Win10\r\n', 'HP 14 ac198TU N3700 - Laptop giá rẻ nhưng không kém phần sang trọng', 20, 6.99, 'Laptop', 10),
(19, 'Cấu hình phù hợp với game hay ứng dụng nhẹ\r\nMáy sử dụng chip xử lý Pentium, đạt tốc độ tối đa 2.4 GHz mang lại khả năng hoạt động tốt hơn so với các dòng máy cùng phân khúc giá hiện nay.\r\nRAM 2 GB và có thể nâng cấp', 'Laptop ASUS X403SA N3700/2GB/500GB/Win10\r\n', 'ASUS X403SA N3700 là chiếc laptop giá rẻ, cấu hình nhẹ nhàng cùng nhiều cổng kết nối tiện ích cho công việc lẫn học tập.', 20, 6.99, 'Laptop', 10),
(20, 'Cấu hình tốt\r\nLaptop Acer ES1 531 mang trên mình vi xử lý Pentium N3710 tốc độ 1.6 GHz của Intel. Thiết bị có RAM 4 GB cùng một khe trống để bạn có thể nâng lên đến 8 GB sử dụng cho nhu cầu cao hơn.', 'Laptop Acer ES1 531 N3710/4GB/500GB/Win10/KhôngDVD', 'Nếu bạn tìm kiếm một sản phẩm có tính di động cao, mức giá hợp lý trong phân khúc phổ thông, thì laptop Acer ES1 531 sẽ là một sự lựa chọn bạn không nên bỏ qua.', 20, 6.99, 'Laptop', 10),
(21, 'To hơn, không gian làm việc lớn hơn\r\nĐược thiết kế rất to với kích thước ngang lên tới hơn 30 cm, iPad Pro tỏ ra là một chiếc máy hữu hiệu cho công việc nhiều hơn là một chiếc máy giải trí để có thể dễ dàng xách đi mọi nơi.', 'Máy tính bảng iPad Pro Wifi Cellular 128GB', 'Giải trí, công việc, thiết kế sang trọng, tinh tế, mạnh mẽ, uy tín là những gì mà chiếc iPad Pro mang đến cho bạn.', 20, 26.99, 'Tablet', 10),
(22, 'Thiết kế sang trọng\r\nVới những sản phẩm đến từ Apple thì điều ưu tiên và tiên quyết của họ là thiết kế sang trọng và bắt mắt, iPad Pro 9.7 inch được làm từ chất liệu nhôm nguyên khối tạo cho máy một cảm giác cầm nắm đầm tay và cực kì sang trọng.', 'Máy tính bảng iPad Pro 9.7 inch Wifi Cellular 256GB', 'Chiếc iPad Pro 9.7 inch có cấu hình cực kì mạnh mẽ, sang trọng và trên hết là kích thước được làm gọn hơn.', 20, 26.59, 'Tablet', 10),
(23, 'Thiết kế sang trọng\r\nVới những sản phẩm đến từ Apple thì điều ưu tiên và tiên quyết của họ là thiết kế sang trọng và bắt mắt, iPad Pro 9.7 inch được làm từ chất liệu nhôm nguyên khối tạo cho máy một cảm giác cầm nắm đầm tay và cực kì sang trọng.', 'Máy tính bảng iPad Pro 9.7 inch Wifi Cellular 128GB', 'Chiếc iPad Pro 9.7 inch có cấu hình cực kì mạnh mẽ, sang trọng và trên hết là kích thước được làm gọn hơn.', 20, 22.49, 'Tablet', 10),
(24, 'To hơn, không gian làm việc lớn hơn\r\nVới kích thước lớn nên chiếc iPad Pro tỏ ra là một chiếc máy hữu hiệu cho công việc nhiều hơn là một chiếc máy giải trí để có thể dễ dàng xách đi mọi nơi.', 'Máy tính bảng iPad Pro Wifi 32GB', 'Giải trí, công việc, thiết kế sang trọng, tinh tế, mạnh mẽ, uy tín là những gì mà chiếc iPad Pro mang đến cho bạn.', 20, 19.99, 'Tablet', 10),
(25, 'Thiết kế sang trọng\r\niPad Pro 9.7 inch có kích thước và thiết kế rất giống với iPad Air 2 nhưng vẫn có sự khác biệt là có thêm màu vàng hồng rất hiện đại và có đến 4 chiếc loa ngoài đem đến trải nghiệm tốt hơn.', 'Máy tính bảng iPad Pro 9.7 inch Wifi 128GB', 'iPad Pro 9.7 inch được nâng cấp chất lượng hiển thị, chất lượng camera tốt hơn rất nhiều, cùng các phụ kiện như bàn phím rời và bút Pencil chuyên dụng.', 20, 19.49, 'Tablet', 10),
(26, 'Nhỏ hơn, mạnh hơn và tinh tế hơn là những cụm từ dùng để miêu tả iPad Pro 9.7 inch vừa mới ra mắt của Apple so với iPad Pro 12.9 inch trước kia.', 'Máy tính bảng iPad Pro 9.7 inch Wifi Cellular 32GB', 'iPad Pro 9.7 inch Wifi Cellular 32GB – Đẳng cấp, mạnh mẽ và thời trang', 20, 18.99, 'Tablet', 10),
(27, 'Cảm biến vân tay\r\nĐây chính là điểm nâng cấp khác biệt so với iPad Air đời đầu, nâng cao khả năng bảo mật hơn nữa của máy.', 'Máy tính bảng iPad Air 2 Cellular 64GB', 'iPad Air 2 Cellular 64GB có bộ nhớ trong nhiều hơn, dành cho bạn có nhu cầu lưu trữ dữ liệu, hình ảnh.', 20, 15.99, 'Tablet', 10),
(28, 'Sau khi giới thiệu chiếc iPad Pro 12.9 inch thì Apple đã đưa đến người tiêu dùng thêm một phiên bản mini khác của chiếc iPad cỡ lớn này với màn hình 9.7 inch với cấu hình tương đương.', 'Máy tính bảng iPad Pro 9.7 inch Wifi 32GB', 'iPad Pro 9.7 inch – Máy tính bảng cao cấp, hiệu năng mượt mà', 20, 15.9, 'Tablet', 10),
(29, 'Kết nối mạng qua nhiều cách\r\nMáy có kết nối wifi chuẩn Wi-Fi 802.11 a/b/g/n/ac cho phép bạn duyệt web nhanh hơn, ngoài ra khi không thể vào wifi, bạn có thể tùy chỉnh bật 3G/4G để tiếp tục lên mạng.', 'Máy tính bảng iPad Mini 4 Wifi Cellular 64GB', 'iPad Mini 4 Wifi Cellular 64GB với dung lượng lớn hơn, cho bạn thêm sự lựa chọn với kết nối mạng 3G/4G cùng cấu hình mạnh mẽ.', 20, 14.99, 'Tablet', 10),
(30, 'Cảm biến vân tay\r\nLà cải tiến lớn nhất của dòng iPad mini khi iPad Mini 3 được trang bị cảm biến, tăng khả năng bảo mật máy lên cao hơn. Cách sử dụng đơn giản, nhận diện nhanh chóng mang đến nhiều tiện lợi.', 'Máy tính bảng iPad Mini 3 Retina Cellular 64GB', 'iPad Mini 3 Retina Cellular 64GB mang lại cho người dùng hiệu năng mạnh, tiện ích 3G/4G cùng cảm biến vân tay cho dòng mini.', 20, 13.99, 'Tablet', 10);
